### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by hodahakim** [NRTC/quick-start-guide#61]
- manpages (manual page):
	- man command
	- online manpage
- regex (Regular Expression)
- patterns
- stdout/stdin/stderr
- redirectors (pipe, >, <)
- grep
- Script File:
	- batch file  (in Microsoft Windows)
		PowerShell
		cmd (Command Prompt)
	- shell script (in Unix-like operating systems)
		shell
		terminal
- dpkg/apt
- Environment variables

**Comment by rezaeimohammad** [comment]
#69 fixed it
